name: fbinv
main: com.spinalcraft.mc.fanboatinv.fbinv.fbinv
version: 0.1
commands:
  fbinv:
    description: This is a demo command.
    usage: /<command> [player] [kit]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>