name: fbinv
main: com.spinalcraft.mc.fanboatinv.fbinv.fbinv
version: 0.1
commands:
  fb:
    description: Access fb inventory system
    usage: /<command> [subcommand]
    permission: <plugin name>.basic
    permission-message: You don't have <permission>